#!/usr/bin/env python3
# Auto-generated training script for COS-DMS Department
# Generated by department_training_strategy.py

import sys, os, json, time, pickle
from typing import Optional
import pandas as pd
import numpy as np

from ray import init
from ray.air import RunConfig
from ray.tune import CLIReporter, Tuner
from ray.air.config import CheckpointConfig
from ray.tune.logger import TBXLoggerCallback
from ray.tune.registry import register_env

from ray.rllib.algorithms.ppo import PPOConfig
from ray.rllib.algorithms.callbacks import DefaultCallbacks
from ray.rllib.env.wrappers.pettingzoo_env import ParallelPettingZooEnv

# Add your project path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from envs.timetabling_env import ParallelTimetablingEnv

# Ray configuration
SPILL_DIR = "C:/ray_spill"; TEMP_DIR = "C:/ray_temp"
os.makedirs(SPILL_DIR, exist_ok=True); os.makedirs(TEMP_DIR, exist_ok=True)
os.environ["RAY_object_spilling_config"] = json.dumps(
    {"type": "filesystem","params": {"directory_path": SPILL_DIR}}
)

def load_department_data():
    """Load cached data and filter for COS-DMS only"""
    
    # Load full cached data
    if not os.path.exists('cached_environment_data.pkl'):
        print("Error: cached_environment_data.pkl not found!")
        print("Run 'python preprocess_data.py' first to create the cache.")
        raise FileNotFoundError("Run preprocessing first")
    
    with open('cached_environment_data.pkl', 'rb') as f:
        data = pickle.load(f)
    
    # Load department-specific CSV
    dept_df = pd.read_csv('department_data/dept_COS-DMS.csv')
    print(f"Loaded {len(dept_df)} rows for COS-DMS")
    
    # Filter subjects to only include COS-DMS subjects
    dept_subjects = set(dept_df['Subject'].tolist())
    
    # Filter all arrays to match department subjects
    filtered_indices = []
    for i, subj in enumerate(data['subject_names']):
        if subj in dept_subjects:
            filtered_indices.append(i)
    
    # Update data with filtered information
    filtered_data = data.copy()
    filtered_data['num_subjects'] = len(filtered_indices)
    filtered_data['subject_names'] = [data['subject_names'][i] for i in filtered_indices]
    filtered_data['subject_departments'] = [data['subject_departments'][i] for i in filtered_indices]
    filtered_data['subject_areas'] = [data['subject_areas'][i] for i in filtered_indices]
    filtered_data['subject_allowed_rooms'] = [data['subject_allowed_rooms'][i] for i in filtered_indices]
    filtered_data['subject_section_idx'] = [data['subject_section_idx'][i] for i in filtered_indices]
    filtered_data['subject_teacher_idx'] = [data['subject_teacher_idx'][i] for i in filtered_indices]
    
    print(f"Filtered to {filtered_data['num_subjects']} subjects for COS-DMS")
    return filtered_data

def make_department_env():
    """Create environment for COS-DMS only"""
    data = load_department_data()
    
    env = ParallelTimetablingEnv(
        num_teachers=data["num_teachers"],
        num_subjects=data["num_subjects"],
        num_days=data["num_days"],
        num_timeslots=data["num_timeslots"],
        room_codes=data["room_codes"],
        subject_codes=data["subject_names"],
        subject_campuses=data["subject_departments"],
        subject_areas=data["subject_areas"],
        subject_allowed_rooms=data["subject_allowed_rooms"],
        subject_section_idx=data["subject_section_idx"],
        section_labels=data["section_labels"],
        max_classes_per_teacher=4,
        teacher_max_classes_map=data["teacher_max_classes_map"],
        subject_teacher_idx=data["subject_teacher_idx"],
        area_teacher_indices=data["area_teacher_indices"],
        
        # PBT-optimized reward values
        strict_teacher_match=False,
        r_teacher_match=2.0,
        r_teacher_mismatch=-0.5,
        r_area_match=1.5,
        r_area_mismatch=-1.0,
        r_workload_balance=0.8,
        base_success_reward=0.05,
        
        # Department-optimized settings
        include_focus_scalar=True,
        include_focus_tor_scalar=False,
        include_section_features=True,
        include_workload_features=True,
        enable_communication=True,
        use_action_masks=True,
        max_timesteps=100,
        enable_repair_pass=False,
    )
    
    # Set labels
    env.subject_names = data["subject_names"]
    env.teacher_labels = data["teacher_id_to_name"]
    env.day_labels = data["day_labels"]
    env.timeslot_labels = data["timeslot_labels"]
    
    return ParallelPettingZooEnv(env)

if __name__ == "__main__":
    print("=" * 60)
    print("TRAINING COS-DMS DEPARTMENT")
    print("=" * 60)
    
    init(ignore_reinit_error=True, include_dashboard=False, _temp_dir=TEMP_DIR)
    register_env("dept_env", lambda cfg: make_department_env())
    
    # Test environment
    dummy = make_department_env()
    raw = dummy.par_env
    first_saha = [a for a in raw.agents if a.startswith("saha_")][0]
    
    print(f"Department environment loaded:")
    print(f"   - Subjects: {raw.num_subjects}")
    print(f"   - Teachers: {raw.num_teachers}")
    print(f"   - Global slots: {raw.global_slot_count}")
    
    # Department-optimized training configuration
    ppo_cfg = (
        PPOConfig()
        .environment(env="dept_env", disable_env_checking=True)
        .framework("torch")
        .rollouts(
            num_rollout_workers=2,
            rollout_fragment_length=64,
            batch_mode="complete_episodes",
            enable_connectors=False,
            compress_observations=True,
            num_envs_per_worker=1,
        )
        .training(
            # PBT-optimized + department-specific
            gamma=0.98,
            lr=1e-4,
            train_batch_size=512,
            sgd_minibatch_size=256,
            num_sgd_iter=5,
            clip_param=0.2,
            vf_clip_param=50000.0,
            entropy_coeff=0.02,
            vf_loss_coeff=0.5,
            grad_clip=10.0,
        )
        .resources(
            num_gpus=1,
            num_gpus_per_worker=0,
            num_cpus_for_local_worker=2,
        )
        .multi_agent(
            policies={"dept_policy": (
                None,
                raw.observation_spaces[first_saha],
                raw.action_spaces[first_saha],
                {"model": {"custom_model": "saha_masked_head"}, "lr": 1e-4},
            )},
            policy_mapping_fn=lambda agent_id, episode, **kwargs: "dept_policy",
            policies_to_train=["dept_policy"],
            count_steps_by="env_steps",
        )
        .evaluation(
            evaluation_interval=20,
            evaluation_duration=2,
            evaluation_duration_unit="episodes",
            evaluation_num_workers=1,
            evaluation_config={"explore": False},
        )
        .debugging(seed=42)
        .experimental(_enable_new_api_stack=False, _disable_preprocessor_api=False)
    )

    config = ppo_cfg.to_dict()

    run_cfg = RunConfig(
        stop={"training_iteration": 60},
        local_dir="C:/ray_logs",
        name="PPO_COS-DMS_Department",
        checkpoint_config=CheckpointConfig(checkpoint_frequency=25, checkpoint_at_end=True, num_to_keep=3),
        verbose=1,
        log_to_file=f"COS-DMS_training.log",
    )

    print(f"Starting COS-DMS department training...")
    print(f"Expected completion: ~20 minutes")
    
    tuner = Tuner("PPO", param_space=config, run_config=run_cfg)
    results = tuner.fit()

    print(f"\nCOS-DMS DEPARTMENT TRAINING COMPLETED!")
    try:
        best = results.get_best_result(metric="episode_reward_mean", mode="max")
        print(f"Best reward: {best.metrics.get('episode_reward_mean')}")
        
        # Save department model info
        model_info = {
            "department": "COS-DMS",
            "best_reward": best.metrics.get('episode_reward_mean'),
            "checkpoint_path": str(best.checkpoint),
            "training_iterations": 60,
            "subjects_count": raw.num_subjects
        }
        
        with open(f'COS-DMS_model_info.json', 'w') as f:
            json.dump(model_info, f, indent=2)
            
        print(f"Model info saved to COS-DMS_model_info.json")
        
    except Exception as e:
        print(f"Training completed. Details: {e}")
